### ISSUE TITLE
[CT-903] Configure more connection retries for CI tests

### ISSUE THREAD

**Issue by nathaniel-may** [dbt-labs/dbt-redshift#142]
The upstream postgres adapter [just added exponential backoff](https://github.com/dbt-labs/dbt-core/pull/5503) when `retries` > 1. We should change our retries settings for our dbt projects that run in CI to reduce RedShift failures. I suspect that can be set somewhere in [here](https://github.com/dbt-labs/dbt-redshift/blob/main/tests/integration/base.py).

**Comment by jtcohen6** [comment]
Needs to be added in two places, since we have two test frameworks :)

https://github.com/dbt-labs/dbt-redshift/blob/7abf0464e27499524a8d60e6e182db98bfa902c2/tests/conftest.py#L9-L21

https://github.com/dbt-labs/dbt-redshift/blob/7abf0464e27499524a8d60e6e182db98bfa902c2/tests/integration/base.py#L146-L166
