### ISSUE TITLE
[CT-1061] Remove `ra3_node` profile config?

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-redshift#171]
### Describe the feature

Currently, if you're using "2nd gen" Redshift nodes, dbt-redshift will try to raise a helpful error if it thinks you're doing something disallowed, by trying to query/catalog a table that lives in a different database:
https://github.com/dbt-labs/dbt-redshift/blob/fe91015ac6361c48531b439ac72d3f477d9cc07b/dbt/adapters/redshift/impl.py#L75-L78

(As it turns out, this exception is raised inconsistently — yes during `docs generate`, but seemingly not during `dbt run` if you've defined sources with other `database` values.)

With the advent of RA3 nodes in 2019 (!), you can _opt into_ this functionality by setting an `ra3_node: true` configuration in `profiles.yml`

I think there's a legitimate case to just remove the exception entirely, and treat `verify_database` as a no-op.

### Describe alternatives you've considered
Leaving `ra3_node` as a profile configuration, but setting it to `true` by default, now that the majority (we think) of `dbt-redshift` users are running on RA3 nodes.

### Additional context
I'm trying to remind myself of why we went for the opt-in config in the first place, rather than removing this gate completely. The relevant issues are from earlier last year:
- https://github.com/dbt-labs/dbt-core/issues/3179
- https://github.com/dbt-labs/dbt-core/issues/3236

I recall our rationale coming down to trying to answer the question: Are RA3 nodes the future of Redshift? Or, if 2nd-gen node types are sticking around, how fundamental is the fork in functionality between 2nd-gen and 3rd-gen+ nodes?

I don't remember getting crystal-clear answers to those questions. In retrospect, the `ra3_node` config was a highly conservative approach which assumed that:
- 2nd-gen and 3rd-gen node types were sticking around for some time (mostly true)
- There would be many more functional gaps as RA3 nodes added more and more capabilities, such that dbt would need to be able to check a conditional config — this hasn't really proven to be the case

### Who will this benefit?
Having profile configurations where they're not truly needed leads to:
- potential confusion for end users
- documentation maintenance burden
- additional work for dbt Cloud to support those profile configurations

**Comment by fredmny** [comment]
Hey, @jtcohen6 
I'd like to further discuss this issue, since it's quite confusing, because of the lack of clarity around it. I don't necessarily think that this config needs to be removed, but we need to make it clearer. What I mean:
- When you get the error message and search the docs / Google you find the following:
  - [This page](https://docs.getdbt.com/docs/core/connect-data-platform/redshift-setup#authentication-methods) which does not make it clear what the default value is, and since the example `profiles.yml` sets it to `true`, one might interpret that this is the default value (since some technical documentation uses this pattern -> leaving the example config with the default value)
  - [This release note for dbt Cloud](https://docs.getdbt.com/docs/dbt-versions/release-notes/aug-2022/support-redshift-ra3.md) which states that the default value for the parameter is `true`. If you found this page through a docs search you may not realize this is true just for dbt Cloud or even assume that this would be consistent through dbt-core and dbt Cloud (which it should be in my opinion)
  - The current issue, which made it kinda clear that the default value is `false` when reading the proposed alternative

So my suggestion is to:
- Set the default value to `true` (which was the alternative solution you proposed)
- Alternatively, at least update the docs to make it clear which the default value is.

I'd be super happy to contribute with any if you could just point me in the right direction

**Comment by colin-rogers-dbt** [comment]
closing as this config updates will be handled in #217
