### ISSUE TITLE
[CT-1617] Materialization to create external tables (Redshift first)

### ISSUE THREAD

**Issue by matt-winkler** [dbt-labs/dbt-redshift#24]
### Describe the feature
When using Redshift Spectrum, dbt is able to stage external tables stored in S3 and do useful things such as declaring the source data format (csv, json, parquet, etc.). The idea is to create a new `materialization` (potentially "external" would work) option which would handle persisting query results and enable a few capabilties:

- Specifying a location to output partitioned results generated by a model's sql
- Specifying the output format (csv, json, parquet) and compression where applicable
- Control over the partitioning logic (e.g. use a defined set of columns to create partitions in the lake)
- For Redshift, ability to `CLEAR PATH` to overwrite existing partitions in the lake

### Describe alternatives you've considered
The implementation of `create_external_table` [here](https://github.com/dbt-labs/dbt-external-tables/blob/0.7.1/macros/plugins/redshift/create_external_table.sql) accomplishes this when triggered by a `run-operation`. The goal here is to make that logic a materialization so that it can become part of the `dbt run` pipeline.

### Additional context
Believe this is relevant for any of the databases currently supported in the external tables package: 

- Redshift (Spectrum)
- Snowflake
- BigQuery
- Spark
- Synapse
- Azure SQL

### Who will this benefit?
dbt Users who have existing infrastructure that leverages a more data lake centric approach for managing persistence will benefit from this. They can use dbt and the warehouse as an ephemeral compute / transform layer, and then persist the data to a file store, which enables other tools (e.g. AWS Glue / Athena) to query the results using existing analytical patterns.

### Are you interested in contributing this feature?
Yes.

**Comment by vergenzt** [comment]
@jtcohen6 @matt-winkler my team is investigating building this feature for our own needs, and would be interested in learning about whether we could contribute it back. I've done some digging & experimentation on approach, isolated a few definite next steps, & narrowed down the final approach to two primary options. Would you mind reviewing and weighing in on (a) which option you suggest and (b) whether you'd be open to this getting merged in?

## Motivation

- My team wants to store model results outside the database (in S3).
- dbt, on the other hand, expects to "... *[only do] the T in ELT (Extract, Load, Transform) processes –* **it doesn’t extract or load data**, but it’s extremely **good at transforming data that’s already loaded into your warehouse**." ([What is dbt? | dbt Docs](https://docs.getdbt.com/docs/introduction))
- Redshift lets us pretend that data in S3 is "in the warehouse".
  - But it has some important differences from standard tables.
  - Those differences make it not (*yet*) compatible with dbt for model output materialization.
  - Can we *make* it compatible? 


## Context

Sharing to make sure I'm understanding correctly:

### dbt materializations

- A dbt materialization is a registered^ adapter-specific^ Jinja macro^.
  - ^*registered* → declared via {% materialization <*name*>… %} instead of {% macro <*name*>… %}
  - ^*adapter-specific* → different database adapters can have different implementations, e.g.
      {% materialization <*name*>, **default** %} … {% endmaterialization %}
      {% materialization <*name*>, **adapter='redshift'** %} *...* {% endmaterialization %}
  - ^*macro* → compiles down to a function with parameters (incl. "context") & return value

- [Called](https://github.com/dbt-labs/dbt-core/blob/v1.0.6/core/dbt/task/run.py#L253-L282) by `dbt run` for each model with [Jinja context](https://github.com/dbt-labs/dbt-core/blob/v1.0.6/core/dbt/context/providers.py#L1227-L1297) that includes:
  - `sql` → compiled-to-string [select statement](https://docs.getdbt.com/docs/building-a-dbt-project/building-models#:~:text=a%20model%20is%20a%20select%20statement) for the current model
  - `pre_hooks` / `post_hooks` → compiled-to-string SQL for current model's [pre & post hooks](https://docs.getdbt.com/reference/resource-configs/pre-hook-post-hook)

### "Materializations generally take the following shape:"

> - *[1.] Prepare the database for the new model [...]*
> - *[2.] Execute any sql required to implement the desired materialization* [...]
> - *[3.] Clean up the database as required* [...]
>
> [Creating new materializations # *Anatomy of a materialization* | dbt Docs](https://docs.getdbt.com/docs/guides/creating-new-materializations#anatomy-of-a-materialization)

### Naive table materialization

A (hypothetical) naive table materialization might look like:

- *[1.] Prepare the database for the new model [...]*

  **drop table if exists [m]**

- *[2.] Execute any sql required to implement the desired materialization [...]*

  **create table [m] as (sql)**

- *[3.] Clean up the database as required [...]*

  **// no-op**

However this would have some problems:

- Prior data unavailable while running **CTAS [m]**.
  (Could be a while if **m** is big.)
- Prior data unavailable until manually restored/rerun if **CTAS [m]** fails.
  (Could be a *long* while, regardless of size of **m**.)

### Pseudo-transactional table materialization

(Hypothetical) improvement:

- *[1.] Prepare the database for the new model [...]*

  **drop table if exists [m_tmp] &&**
  **drop table if exists [m_bak]**

- *[2.] Execute any sql required to implement the desired materialization [...]*

  **create table [m_tmp] as (sql)**
  **&& alter table [m] rename to [m_bak]**
  **&& alter table [m_tmp] rename to [m]**

- *[3.] Clean up the database as required [...]*

  **drop table if exists [m_bak]**

This would resolve the first two problems:

- X Prior data only unavailable briefly, for duration of table rename.
- X Prior data remain in place if **create table [m_tmp] as (sql)** fails.

but introduces one of its own:

- Leaves garbage behind if **create table [m_tmp] as (sql)** fails.

### Current actual table materialization

According to my reading of [the source](https://github.com/dbt-labs/dbt-core/blob/v1.0.6/core/dbt/include/global_project/macros/materializations/models/table/table.sql), the built-in table materialization as implemented today essentially does the following:

- *[1.] Prepare the database for the new model [...]*

  drop table if exists [m_tmp] &&
  drop table if exists [m_bak]

- *[2.] Execute any sql required to implement the desired materialization [...]*

  **In transaction: [**
    create table [m_tmp] as (sql)
    && alter table [m] rename to [m_bak]
    && alter table [m_tmp] rename to [m]
  **]**

- *[3.] Clean up the database as required [...]*

  drop table if exists [m_bak]

This addresses all three problems:

- Prior data only unavailable briefly, for duration of table rename.
- Prior data remain in place if **create table [m_tmp] as (sql)** fails.
- No garbage left behind if **create table [m_tmp] as (sql)** fails.


## Transactional "external table" materialization? 

- *[1.] Prepare the database for the new model [...]*

  drop table if exists [m_tmp] && drop table if exists [m_bak]

- *[2.] Execute any sql required to implement the desired materialization [...]*

  In transaction: [
    create **external** table [m_tmp] as (sql)
    && alter **external** table [m] rename to [m_bak]
    && alter **external** table [m_tmp] rename to [m]
  ]

- *[3.] Clean up the database as required [...]*

  drop table if exists [m_bak]

Unfortunately, this doesn't work because:
 1. attempting to "create external table as" in a transaction leads to `ERROR: CREATE EXTERNAL TABLE cannot run inside a transaction block`, ruling out fully transactional external table creation; and 
 2. attempting to rename an external table in any context leads to `ERROR: Unsupported operation. [Cannot rename external tables.]`, ruling out even pseudo-transactional external table creation.


## What options do we have?

### ~~Option 0. [Naive materialization](#naive-table-materialization). Accept availability constraints.~~

Less than ideal; we would like to find a better way.

### ~~Option 1. [Pseudo-transactional](#pseudo-transactional-table-materialization) via rename = [CET w/ same config](https://github.com/awslabs/amazon-redshift-utils/blob/master/src/AdminViews/v_generate_external_tbl_ddl.sql) && delete old.~~

~~Use the external-table-config-DDL-generation script (seemingly written by someone at AWS) to "rename" external tables by creating external table with same config at the new name (*not* create external table *as*; just *create external table*). Manually clean up failures in on-run-end hook.~~

- ~~Pros: No on-cluster storage used.~~
- ~~Cons: Seems very fragile. Generated DDL could break. DDL generation script could break. Underlying views could break. Unclear maintenance ownership.~~

→ We're not comfortable taking on that maintenance burden / risk. Pretty sure another option would be better.

### Option 2a. "[Transactional](#current-actual-table-materialization)", via table materialization + on-run-end hook

Literally configure the models to materialize as table, then add an on-run-end hook to "create external table as select * from {{ model }}" + "drop table {{ model }}" for every model that got built.

Pros: Simple. No change to materializations.

Cons: dbt manifest's recorded model output locations would be inaccurate, which precludes partial rebuilds and inter-project dependencies. Also, the cluster has to have sufficient capacity to store all model results during the run -- though this storage is reclaimed after the on-run-end hook.

### Option 2b. "[Transactional](#transactional-external-table-materialization)", via front-loading option 2a logic into per-model materialization

So the steps would be:

- *[1.] Prepare the database for the new model [...]*

  drop table if exists [m_tmp] ***[in on-cluster schema]***

- *[2.] Execute any sql required to implement the desired materialization [...]*

  CTAS [m_tmp] ***[in on-cluster schema]***
  && drop table if exists [m] ***[in external schema]***
  && CET [m] ***[in external schema]*** as `select * from` [m_tmp]

- *[3.] Clean up the database as required [...]*

  drop table if exists [m_tmp] ***[from on-cluster schema]***

I assume that in order for dbt's manifest to be accurate, the schema returned by `generate_schema_name` would need to refer to the final destination, correct? In which case, for this option, the "schema" for a model as declared by `generate_schema_name` should refer to an already-existing external schema. And we would probably specify the name of the temporary on-cluster schema (used for its temporary transactional guarantees) via a model configuration.

Obviously, this option introduces substantial added complexity. But it gets you more "correctness" -- future partial dbt runs would find the outputs in the correct spot, dbt docs' schema names would be accurate, etc.

### Option 2c. "[Transactional](#transactional-external-table-materialization)", via 2b but with private per-session temp tables instead of real on-cluster schema?

This option just occurred to me as I was preparing to post this comment! This would obviate the need for the model configuration & having an extra schema lying around.

Are there limitations I'm not aware of that would prevent this approach from working?

### Option 3. Pseudo-transactional at schema level

This option would be the most different from what dbt does currently, but it's what I've personally been interested in for a while. Essentially, can we broaden the scope of dbt's "create as temp" + "rename on success" approach to apply at the *schema* level instead of the individual table level?

Consider the following:

- on-run-start = create external schema if not exists [s_tmp]
- materialization impl = [naive](#naive-table-materialization), into [s_tmp] (won't even have to "drop table [m]" though since s_tmp is fresh for this run!)
- on-run-end =
  	on success → drop schema if exists cascade [s] && rename schema [s_tmp → s]
  	on failure → drop schema if exists cascade [s_tmp]  *(or keep it around for troubleshooting if you want!)*

This would require:

- configurations for S3 location, file type, IAM role, etc. - presumably in model configs?
- permission to create new external schemas and new Glue catalogs



## Things we'll want to do regardless of approach

1. Add an adapter configuration parameter to allow setting [connection.set_session(autocommit=True)](https://www.psycopg.org/docs/connection.html#connection.set_session) in [dbt-postgres connection class](https://github.com/dbt-labs/dbt-core/blob/v1.0.6/plugins/postgres/dbt/adapters/postgres/connections.py#L121-L128)? Not sure if that's the right place for this, but that setting will be very helpful to not have to constantly `commit;` our way out of psycopg2-auto-started transactions.

   Would you be open to merging something like this?

2. Fix [dbt-labs/dbt#2289](https://github.com/dbt-labs/dbt/issues/2289). I think I've got a workable solution for this.

3. Figure out how to clean up prior runs' data out of S3. The only SQL-runnable option for doing this that I've found is Redshift's UNLOAD statement's CLEANPATH option, with which we could unload an empty select statement to clear an S3 prefix. (Even that leaves a single metadata object in the S3 path though, so we'd still need to use new prefixes for every run. But at least we wouldn't be leaving around whole datasets to store indefinitely.)

   Alternatively, we could just run a recurring cleanup job out of band from dbt runs.

**Comment by Fleid** [comment]
Re-opening as #175 has brought the topic back on top (#175 was closed as duplicate).

**Comment by Fleid** [comment]
Our current rule to decide how to solve these issues is:

### Can this problem be solved in user land? Is there a decent work around?

Here it seems like yes, as demonstrated in #175:
> "materializing the model as view and then use a post hook to create an external table from the view."

That's not the most seamless experience, but it works.

### If not, can this problem be solved via a contribution?

You can create your own [materialization](https://docs.getdbt.com/guides/legacy/creating-new-materializations), as has been discussed in this thread.

Now we need to look again at the 3 objections @vergenzt you brought up at the end of the immensely useful "wall of text" above. Are these absolutely blocking? What can we do about them?

### If not, then maybe dbt Labs should solve it
 
Which here we are considering, not in itself but to support longer plans toward cross-warehouse projects (we will need all sorts of external tables for that) for [1.5+](https://github.com/dbt-labs/dbt-core/blob/main/docs/roadmap/2022-08-back-for-more.md).

A lot of hypothetical here, and we need to think about a common interface for external tables across all warehouses to target most warehouses. I'm sure we'll have discussions on the topic when time comes.

**Comment by Fleid** [comment]
Thanks for the update @vergenzt.
Do you mind sharing why you pivoted away from external tables, and for what alternative? That is if it's not really specific to your own situation/context. Just wondering if your new approach could be recommended to others :)

**Comment by vergenzt** [comment]
Hi @Fleid! I've since moved teams so not sure if this is still accurate, but I believe the new plan was to use Databricks/Spark more broadly rather than trying to force external table materialization into dbt-redshift.

**Comment by Fleid** [comment]
@dataders FYI

**Comment by dbeatty10** [comment]
@dataders opened a Discussion about adding external table capabilities into dbt Core: https://github.com/dbt-labs/dbt-core/discussions/8617
