### ISSUE TITLE
Getting AccessExclusiveLock for redshift while running dbt

### ISSUE THREAD

**Issue by raajpackt** [dbt-labs/dbt-redshift#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi I have been facing `AccessExclusiveLock` being set via dbt run statements connecting to my redshift datawarehouse.
Wanted to know if that is the type of lock dbt creates.
https://aws.amazon.com/premiumsupport/knowledge-center/prevent-locks-blocking-queries-redshift/

And how to set it to use `AccessShareLock` instead?

### Environment

```markdown
- OS:linux
- Python:3.7
- dbt:
```

**Comment by jtcohen6** [comment]
@raajpackt Yes, dbt-redshift does create and hold an exclusive lock whenever it drops a relation. This is to prevent a much worse error, if `drop cascade` interferes with a concurrent transaction:

https://github.com/dbt-labs/dbt-redshift/blob/a4a040df16cc4d6f74995e3ac4951d88f7b14a24/dbt/adapters/redshift/connections.py#L71-L92

https://github.com/dbt-labs/dbt-redshift/blob/a4a040df16cc4d6f74995e3ac4951d88f7b14a24/dbt/adapters/redshift/impl.py#L33-L49

We know that there are downsides, at scale, to holding long and locking transactions. There's some good discussion of this over in https://github.com/dbt-labs/dbt-redshift/issues/21.

Unfortunately, because this comes up when we need to `drop` objects, it has to be an `AccessExclusiveLock` rather than an `AccessShareLock` (per the [docs](https://aws.amazon.com/premiumsupport/knowledge-center/prevent-locks-blocking-queries-redshift/) you linked above).

I'm going to close this issue, but I'd be happy to re-open if you want to say a bit more about the specific issue you're running into—what other types of locking transactions are you running?
