### ISSUE TITLE
[CT-1828] [Feature] Change rows_affected to return the number of rows rather than -1.

### ISSUE THREAD

**Issue by elongl** [dbt-labs/dbt-redshift#271]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-redshift functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Currently ,the adapter returns `-1` at the `adapter_response.rows_affected`.
I believe the number is retrieved [here](https://github.com/dbt-labs/dbt-core/blob/999ed0b74ccb0e170f2b58029fdbfe3fc7ac83fd/plugins/postgres/dbt/adapters/postgres/connections.py#L188), at the Postgres adapter.
Could we change it to return the accurate number?

### Are you interested in contributing this feature?

Yes.

**Comment by jtcohen6** [comment]
@elongl dbt is just passing along the rowcount from the connection/cursor, without modification. `-1` is the standard for this, per PEP 440 & as adopted by psycopg2:

- https://peps.python.org/pep-0249/#rowcount
- https://www.psycopg.org/docs/cursor.html#cursor.rowcount

> the row count of the last operation if it can’t be determined by the interface.

Specifically, `-1` tends to be returned by `CREATE VIEW` statements; as part of their execution, they do not select or affect a known number of rows. Only when the view is queried (`SELECT`) does the database actually return a specific number of rows.

Are there specific queries you're looking at where you aren't seeing the expected `rowcount`?

It's possible that switching to use the [native Redshift Python connector](https://docs.aws.amazon.com/redshift/latest/mgmt/python-redshift-driver.html) would yield the same or different metadata, depending on whether the AWS team decided to adhere to the DBAPI / PEP 249 standard.

(This is relevant for Snowflake's Python connector as well, which currently has non-standard behavior for `CREATE TABLE AS` statements: https://github.com/snowflakedb/snowflake-connector-python/issues/645)

**Comment by saramn-ber** [comment]
Hi @jtcohen6 , following up on this to provide you with examples:
We are using both dbt incremental models as well as regular select statement dbt models materialised as table. Just the standard dbt functionality. The message captured in this instance is 'Select'
However, this field is working as expected with seeds. and the message returned is 'Insert'.

**Comment by jtcohen6** [comment]
To clarify: Are you seeing `-1` returned for table and incremental models? That would surprise me!

If you're seeing it for models materialized as views, that's actually correct, per the standard set in PEP 249 / DB-API2.

**Comment by dbeatty10** [comment]
@jtcohen6 We live to surprise and delight! In this case, we can give you 1 out of 2...

I'm seeing `-1` for models materialized as `table` for dbt-redshift==1.5.0b2

<img width="871" alt="image" src="https://user-images.githubusercontent.com/44704949/224434613-15abf275-02bc-41e3-b9dd-3df43e98905e.png">

Two-fold proposal:
1. [Feature] use `N/A` (or nothing!) instead of `-1` for views (or really any case where the driver returns -1)
1. [Bug] Fix `-1` for tables (potentially by aligning with the feature above)

**Comment by Fleid** [comment]
I'm stealing this for now, Jeremy has enough to do outside of Redshift, and this looks like a Redshift specific issue?
Trying to reproduce now.

**Comment by Fleid** [comment]
I think we're mixing two things here. What you screen-shotted Doug, is a duplicate of #373
The original issue was created at the time of 1.4, so is something else entirely.

And on this, we're back to `awaiting_response`.
In 1.4, `dbt-redshift` doesn't give you the count of rows processed. Only `dbt-postgres` does.
Is this an ask to make it visible in the log? In which case we will need to check that its value is returned properly.
Or is there something else?

**Comment by Fleid** [comment]
And the bot is fighting me :(

**Comment by isaacsantelli** [comment]
@Fleid i was just wondering if there's been any movement on this. We're currently running dbt 1.6 and running into the same issue?

also hi we met at coalesce this year 👋

**Comment by dbeatty10** [comment]
@isaacsantelli we're likely to leave this particular issue as closed.

But feel free to create a [new feature request](https://github.com/dbt-labs/dbt-redshift/issues/new?assignees=&labels=enhancement%2Ctriage&projects=&template=feature-request.yml&title=%5BFeature%5D+%3Ctitle%3E) to utilize [`redshift_rowcount`](https://github.com/aws/amazon-redshift-python-driver/blob/1b4b03229f0cc4592e98cb293ec83044db0f8043/redshift_connector/cursor.py#L134) instead of [`rowcount`](https://github.com/aws/amazon-redshift-python-driver/blob/1b4b03229f0cc4592e98cb293ec83044db0f8043/redshift_connector/cursor.py#L123) (as mentioned [here](https://github.com/aws/amazon-redshift-python-driver/issues/73#issuecomment-1031796309)).
