### ISSUE TITLE
[ADAP-504] [Regression] cannot run inside a transaction block

### ISSUE THREAD

**Issue by olivierdet** [dbt-labs/dbt-redshift#425]
### Is this a new bug in dbt-redshift?

- [X] I believe this is a new bug in dbt-redshift
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

We have created a basic macro to create database. 

This does not work anymore using the version 1.5

We have the following error message 

```
Encountered an error while running operation: Database Error
  CREATE DATABASE cannot run inside a transaction block
```

### Expected Behavior

The macro should work as worked in the version 1.4

### Steps To Reproduce

Execute the following macro with dbt redshift v1.5
```
{% macro create_ci_database(git_version) %}

{% set create_command %}
    CREATE DATABASE z_ci_{{ git_version }} ;
{% endset %}

{% do run_query(create_command) %}

{{ log("Created database redshift z_ci_" ~ git_version, info=True) }}

{% endmacro %}
```

### Environment

```markdown
- OS:
- Python:
- dbt-core: 1.5.0
- dbt-redshift: 1.5.0
```

**Comment by olivierdet** [comment]
We're using `run-operation`

**Comment by dbeatty10** [comment]
Thanks again for reporting this @olivierdet.

I was able to reproduce that this fails for dbt-redshift 1.5.0 but works for 1.4.x 👍 

### Reprex
See below for the macro and commands I used.

`macros/my_macros.sql`
```sql
{% macro create_ci_database() %}

{% set database = "dbt_dbeatty" %}

{% set create_command %}
    CREATE DATABASE {{ database }}
{% endset %}

{{ log(create_command, info=True) }}

{% do run_query(create_command) %}

{{ log("Created redshift database " ~ database, info=True) }}

{% endmacro %}
```

Try to run the macro:
```shell
dbt --debug run-operation create_ci_database
```

**Comment by VersusFacit** [comment]
Looks like the answer is to sneak a [connection.autocommit=True](https://www.psycopg.org/docs/connection.html#connection.autocommit) in the _right_ place. I'm looking for something not _too_ blunt_.

**Comment by VersusFacit** [comment]
The Redshift connector likely in its design philosophy does not allow CREATE DATABASE/VACUUM to be run without the autocommit feature true. But because how adapters are defined, we cannot preserve the original workflow without some extremely painful lift:
- go back to psycopg2
- completely change the MacroTask's thread allocation model
- completely change how all threads are allocated / when (i.e. the env var solution)

I'm going to merge #458 to give users a path forward. However, the hope of this issue cannot be attained without us going back to the drawing board.
