### ISSUE TITLE
[ADAP-570] [Regression] Why dbt-redshift 1.5+ is available on pypi knowing the issues with it?

### ISSUE THREAD

**Issue by alejandrofm** [dbt-labs/dbt-redshift#460]
### Is this a regression in a recent version of dbt-redshift?

- [X] I believe this is a regression in dbt-redshift functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

Sorry, didn't know where to post this, but it's been 3 weeks from the last release that needs timeout tweaking to make it work.

### Expected/Previous Behavior

Why is that release still exists? dbt-redshift should roll back to the last fully working version <1.5 I guess.

### Steps To Reproduce

- Install 1.5+, note that this version needs to be tweaked to run.
- Rollback to previous version

### Environment

```markdown
- OS:
- Python:
- dbt-core (working version):
- dbt-redshift (working version):
- dbt-core (regression version):
- dbt-redshift (regression version):
```

**Comment by dbeatty10** [comment]
Thank you for reaching out @alejandrofm !

We've had several issues during our switch from `psycopg2` to `redshift_connector` as the underlying Python connector, and https://github.com/dbt-labs/dbt-redshift/issues/427 is one of them. We're sorry for how this affects you and others.

Fully reverting back to 1.4.0 has its own downsides that we are unwilling to adopt. Instead our approach is to provide fixes or workarounds for dbt-redshift 1.5.x with dbt-redshift 1.4.x as the fall-back for those that can't upgrade yet due to a regression that affects them.

We realize that this might not be satisfactory, but we are doing our best to reestablish parity.

You are welcome to participate in the Discussion here along similar lines: https://github.com/dbt-labs/dbt-redshift/discussions/457

### Workarounds in the meantime

#### Using 1.4.x
To use [1.4.x](https://pypi.org/project/dbt-redshift/1.4.0/) from PyPI, you can do something similar to the following:
```
python3 -m pip install dbt-redshift~=1.4.0
```

#### Timeout workaround

For 1.5.0, you can add an absurdly high timeout [within your `profiles.yml`](https://docs.getdbt.com/reference/warehouse-setups/redshift-setup#password-based-authentication):

```yaml
      connect_timeout: 999999
```

**Comment by alejandrofm** [comment]
Thank you, we had some hiccups here and without the availability of this version, we would waited a little longer.
It resonates with me how the deploy passed tests against a Redshift database, and how can those tests be improved.
Another thing is, because this version isn't working, why not make a "hotfix" release a 1.5.1b that sets by default:
      connect_timeout: 999999
and remove it for the next versions, so the users don't have to hardcode variables for this version only.
Thanks

**Comment by Fleid** [comment]
Excellent question, but I'm moving the conversation to https://github.com/dbt-labs/dbt-redshift/discussions/457
See you there!
