### ISSUE TITLE
[ADAP-609] [CT-2617] [Bug] Database Error   Invalid region provided: net

### ISSUE THREAD

**Issue by Auric-Manteo** [dbt-labs/dbt-redshift#483]
### Is this a new bug in dbt-core?

- [ ] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Command: 

    #dbt --no-use-colors  test --project-dir /home/me/projects/pycharm/dbt/dbt/integration_middleware/ --profiles-dir /home/me/projects/pycharm/dbt/dbt/integration_middleware/
    06:29:22  Running with dbt=1.5.1
    06:29:23  Found 31 models, 60 tests, 0 snapshots, 0 analyses, 348 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups
    06:29:23  
    06:29:23  
    06:29:23  Finished running  in 0 hours 0 minutes and 0.03 seconds (0.03s).
    06:29:23  Encountered an error:
    Database Error
      Invalid region provided: net

    
    dbt --version
    Core:
      - installed: 1.5.1
      - latest:    1.5.1 - Up to date!
    
    Plugins:
      - postgres: 1.5.1 - Up to date!
      - redshift: 1.5.2 - Up to date!

This works fine after downgrading the version to:

    dbt --version
    Core:
      - installed: 1.4.6
      - latest:    1.5.1 - Update available!
    
      Your version of dbt-core is out of date!
      You can find instructions for upgrading here:
      https://docs.getdbt.com/docs/installation
    
    Plugins:
      - postgres: 1.4.6 - Update available!
      - redshift: 1.4.0 - Update available!

### Expected Behavior

The dbt tests are run.

### Steps To Reproduce

Upgrade dbt to said version and execute the tests on a Redshift project with the command I stated.
The profiles.yml (originally generated by airbyte) looks like this:

    config:
      partial_parse: true
      printer_width: 120
      send_anonymous_usage_stats: false
      use_colors: true
    normalize:
      outputs:
        prod:
          dbname: MYDB
          host: MYHOST
          pass: MYPASS
          port: MYPORT
          schema: MYSCHEMA
          threads: 1
          type: redshift
          user: MYUSER
      target: prod

### Environment

```markdown
- OS:Ubuntu 20.04
- Python:3.10.6
- dbt:1.5.1
```

### Which database adapter are you using with dbt?

postgres, redshift

**Comment by dbeatty10** [comment]
Thank you for reporting this @Auric-Manteo 🙏 And thanks @sankeerth1988 for mentioning the new `region` parameter as a viable work around for this scenario 🏅

We made a switch from using `psycopg2` in 1.4 to using `redshift_connector` in 1.5 and there were several issues that arose, including the one you reported. Shortly after our initial release, we included https://github.com/dbt-labs/dbt-redshift/pull/420 in a patch release as a workaround for the issue you experienced.

It's not clear to me if it's even possible for this to be a non-breaking change -- whether or not completely depends on what is possible with `redshift_connector`. Since this is going to require some more research, we've created a spike in https://github.com/dbt-labs/dbt-redshift/issues/484 to investigate this further -- please subscribe and/or comment there.

In the meantime, please let us know if you run into any issues with the new `region` parameter.

**Comment by alison985** [comment]
I'm also running into this but we don't have `profiles.yml` because we're in the Cloud IDE.
