### ISSUE TITLE
[ADAP-656] [Bug] Performance issue with incremental materialization

### ISSUE THREAD

**Issue by sathiish-kumar** [dbt-labs/dbt-redshift#506]
### Is this a new bug in dbt-redshift?

- [X] I believe this is a new bug in dbt-redshift
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When doing incremental materialization with more than 1 unique keys, it performs a DELETE that includes `cast`ing tables into different datatypes. This leads to poor performance on the Redshift side. The customer would like to understand what the bottleneck is and fix it if possible. 

### Expected Behavior

(Customer to add more details around the performance datapoints that they are seeing)

### Steps To Reproduce

1. Create an incremental materialization for the model
2. Run a full refresh of the materialization using `$ dbt run --full-refresh --select my_incremental_model+`
3. See logs

### Relevant log output

```shell
DELETE FROM "database"."dbt_prod_schema"."portal_subscription"
           WHERE(
               md5(cast(coalesce(cast(event_id as varchar), '') || '-' || coalesce(cast(e_tstamp as varchar), '') as varchar))) in (
               select (md5(cast(coalesce(cast(event_id as varchar), '') || '-' || coalesce(cast(e_tstamp as varchar), '') as varchar)))
               from "portal_ subscription__dbt_tmp114443561923"
           );
```
```


### Environment

```
- OS:
- Python:
- dbt-core:
- dbt-redshift:
```


### Additional Context

_No response_

**Comment by jtcohen6** [comment]
If I had to guess - is the `unique_key` here being set to the output of [`dbt_utils.generate_surrogate_key`](https://github.com/dbt-labs/dbt-utils#generate_surrogate_key-source)? That will include casting in order to "safely" concat together values that could be null.

A way to achieve better performance: Actually store that surrogate key as a column in the table. Then, dbt/Redshift will use that (already computed) column value for the `DELETE` + `INSERT`, rather than recomputing it on the fly.
