### ISSUE TITLE
[ADAP-758] [CT-2929] The Materialized Views are not working in v1.6 on redshift as as documented or as expected

### ISSUE THREAD

**Issue by heshamh96** [dbt-labs/dbt-redshift#565]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

it's a long-awaited feature for me so i'm reporting 3 bugs in here ... 

1) the dbt run when issued consecutively against the MV that's configured with on_configuration='apply'  ... it doesn't pick up changes ... and throws an error ... that is mostly solved by manually removing the MV manually from the DB 

2) most of the on_configuration _change Values ... are either documented poorly or really not working ... because the 
"auto_refresh" ,"skip" and the "fail" options are not working and they throw Python errors 

3) if everything is set to run perfectly  ... when ever i try to materialize the MV to have "auto-refresh=True" like
in the configuration of the MV back on dbt v1.5 when i was using the experimental features package of you guys
it's no longer working ... is it set to be supported in this release or not ???? 

4) last but not least .... I need to know what to do to move away from the experimental package of yours to using the officially supported feature ... there is no documentation on that so kindly assist

### Expected Behavior

materialized views should run successfully against multiple dbt runs

it also should support the auto-refresh=ture

and other configs of the on_configuration_change ... should be working as expected

### Steps To Reproduce

configuring the MV's "on_configuration_change" to be anything basically except for apply ... throws a python error

setting the "auto-refresh"  = True also throws an error

### Environment

```markdown
- OS:Pop-OS
- Python:3.10
- dbt:1.6
```

### Which database adapter are you using with dbt?

redshift

```[tasklist]
### materialized views should...
- [ ] run successfully with `on_configuration_change='apply'` after modifying `SELECT` statement and re-running
- [ ] support `auto-refresh=true`
```

**Comment by mikealfare** [comment]
We definitely need to update our docs to reflect the MV implementation; unfortunately this did not happen in time. It appears we got out of sync. Let me get you some quick responses here and we'll work on the rest.


> 1. the dbt run when issued consecutively against the MV that's configured with on_configuration='apply' ... it doesn't pick up changes ... and throws an error ... that is mostly solved by manually removing the MV manually from the DB

- I haven't seen this throw an error; can you please provide an example model?
- can you confirm that you used `on_configuration_change = 'apply'` and not `on_configuration = 'apply'`? The former will not work (hence "it doesn't pick up changes"), but also shouldn't throw an error (so it doesn't explain that part).

> 2. most of the on_configuration _change Values ... are either documented poorly or really not working ... because the
    "auto_refresh" ,"skip" and the "fail" options are not working and they throw Python errors

- "auto_refresh" is not a value for `on_configuration_change`, it's a separate config; are you passing it in as a value, e.g. `on_configuration_change = 'auto_refresh'`? or are you saying that the `auto_refresh` config is not being recognized correctly
- the skip issue is likely a result of out of date docs; `'skip'` should actually be `'continue'`. We decided late in the process to avoid the use of the word "skip" since there are other related statuses that use that value. This throws an error because `on_configuration_change` is an enum. It should instead throw a warning (not an error) that nothing was done to the model.
- "fail" is supposed to raise an error; the intended use is to fail the run if any changes are detected

> 3. if everything is set to run perfectly ... when ever i try to materialize the MV to have "auto-refresh=True" like
    in the configuration of the MV back on dbt v1.5 when i was using the experimental features package of you guys
    it's no longer working ... is it set to be supported in this release or not ????

- `auto_refresh` is supported in this release as a boolean; this is likely a result of out of date docs
  - `auto_refresh=True` results in turning on auto refresh
  - `auto_refresh=False` results in turning off auto refresh
  - if no value is supplied, this config should default to `False` 
- can you please confirm that you used `auto_refresh=True` and not `auto-refresh=True`?

> 4. last but not least .... I need to know what to do to move away from the experimental package of yours to using the officially supported feature ... there is no documentation on that so kindly assist

- this does appear to be a miss; let me see what we can do

**Comment by mrgambal** [comment]
Sorry for my perhaps ignorant guess, but I feel that [this line](https://github.com/dbt-labs/dbt-redshift/blob/main/dbt/include/redshift/macros/materializations/materialized_view.sql#L105) may be missing the 'CASCADE' statement, whether in the experimental repo [analogous code](https://github.com/dbt-labs/dbt-labs-experimental-features/blob/main/materialized-views/macros/default/adapters.sql#L27) had it. That missing qualifier leads to failures during full refresh, e.g.:

```python
13:37:41  Database Error in model daily_conditions_summary (models/staging/daily_conditions_summary.sql)
13:37:41    cannot drop materialized view dashboard_staging.daily_conditions_summary because other objects depend on it
13:37:41    compiled Code at target/run/mc_dw_automation/models/staging/daily_conditions_summary.sql
```.

**Comment by mikealfare** [comment]
Thanks @mrgambal for the information. That does look like an issue, though that also suggests to me that the caching isn't working as expected. We'll look into that.

**Comment by Fleid** [comment]
For:

> last but not least .... I need to know what to do to move away from the experimental package of yours to using the officially supported feature ... there is no documentation on that so kindly assist

The experimental package is, well, experimental, and there is no recommended way to move from it to the new implementation, since the former should not be used in production to get started with.

As such, we don't plan at this date to write a migration doc. We would really appreciate if someone were to write one, and would certainly consider merging it into the experimental repository doc section... :)
