### ISSUE TITLE
[CT-23] syntax error with table backup option

### ISSUE THREAD

**Issue by will-peloton** [dbt-labs/dbt-redshift#60]
### Describe the bug
dbt run fails on syntax error for models that have both backup option and table_attribute set e.g. dist_key

### Steps To Reproduce
run this model 

```
{{ config(backup=False, dist='a', sort='a') }}
select 1 as a
```

### Expected behavior
model should build

### Screenshots and log output
![Screen Shot 2022-01-05 at 1 05 37 PM](https://user-images.githubusercontent.com/73236400/148266807-d9addc2c-7bd3-4aaa-9a18-efbf89caf6cd.png)

### System information
**The output of `dbt --version`:**
```
installed version: 1.0.1
   latest version: 1.0.1

Up to date!

Plugins:
  - snowflake: 0.21.0
  - redshift: 1.0.0
  - postgres: 1.0.1
```

**The operating system you're using:**
Mac
**The output of `python --version`:**
Python 3.8.6
### Additional context
backup option needs to be before table_attribute, which is not the case by looking at complied SQL. This is related to https://github.com/dbt-labs/dbt-redshift/pull/42/files

**Comment by SMeltser** [comment]
I was able to reproduce the issue and agree with Will's original assessment of the root cause.

**Comment by McKnight-42** [comment]
thank you @will-peloton for bringing this up and thank you @SMeltser for verifying and opening a PR toward it, I'm going to go ahead move this to a good first issue and check PR #63

**Comment by VersusFacit** [comment]
👍 To what Matt said 

Since this was let through before because we didn't have a test for this case, would you mind adding a test or two for queries which include backup and various other Redshift options? 

Not to send you out into deep end by yourself. Here's the [class](https://github.com/dbt-labs/dbt-redshift/blob/e8297d58536d2f08b6159d51008df14126c9ff6b/tests/integration/backup_table_tests/test_backup_table_option.py#L6) or thereabouts a test has both the backup option and a dist key/sort key should go!

We'll be happy to lend extra support in making sure this behavior get's encoded as a regression test for future users.
