### ISSUE TITLE
[CT-79] Show a better error message than `SSL SYSCALL error: EOF detected`

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-redshift#66]
### Describe the feature
Occasionally, someone will post in the community Slack because they've run into an inscrutable error message `SSL SYSCALL error: EOF detected`. 

The state of the art seems to be [this post from Jake](https://getdbt.slack.com/archives/C50NEBJGG/p1600199337078600?thread_ts=1600198992.078500&cid=C50NEBJGG) back in the day, recommending a decrease of the `keepalives_idle` value.

If/when this does happen, we should do a better job of explaining what happened and how it can be resolved. It's confusing to be described as an SSL error* _plus_ an end of file error, for it to ultimately be a timeout problem.

*I read it as Single Sockets Layer, which is doubly concerning - is my connection unsafe somehow?

I'd prefer something like `SSL SYSCALL error: EOF detected. The socket was closed unexpectedly, try a lower keepalives_idle value`. (Related: this would be a great candidate for nice shortlinks to read more in the docs @runleonarun)

### Describe alternatives you've considered
-✅ [Updating the docs](https://github.com/dbt-labs/docs.getdbt.com/pull/1038) so that people find out how to fix it when they search the error message
- Copy-pasting the same Slack link for the rest of my life 
 
### Who will this benefit?
What kind of use case will this feature be useful for? Please be specific and provide examples, this will help us prioritize properly.
- Redshift and Postgres users who have a patchy connection

### Are you interested in contributing this feature?
Yeah this seems like the sort of thing I could do, if I knew where the error was raised and how to safely relay it

**Comment by McKnight-42** [comment]
@joellabes Thank you for opening this issue up and the reflecting docs update, I will look for the correct Exception to grab to change in `impl.py` to update to your desired wording and keep you updated on any progress made.

**Comment by VersusFacit** [comment]
@joellabes ! 👋 Thanks for taking the time to write this up. This is something I remember getting frustrated with myself back when I was a Redshift developer. I think it's great to think of the user experience here.

Okay, so, brass tacks:
- this seems to be a connection error, either because:
  - generic network failure
  - (Jake's case) occurs when queries are longer than the timeout period (what strikes me as a distinctly analytics flavored phenomenon since transactions shouldn't take that long, and hence the 240 default) [see this [SO](https://stackoverflow.com/a/63130830)]
- your desire to have a better error message appears simple (e.g. add more text)
- this dbt adapter is not responsible for the implementation of such low level details as keepalive_threads (which waits for the Postgres server to respond after a query completes or fails over for whatever reason)
- this requires:
  - an override of psycopg2 or boto3 natively which we won't be doing
  - catching the DatabaseError exception and writing the message you want in this repo for these two

Further complicating this (from the [postgres docs](https://www.postgresql.org/docs/9.3/libpq-connect.html)):
> `keepalives_idle`: ... This parameter is ignored for connections made via a Unix-domain socket, or if keepalives are disabled. It is only supported on systems where TCP_KEEPIDLE or an equivalent socket option is available, and on Windows; on other systems, it has no effect.

So, Jake's suggestion seemed to have worked for those other users, which is great! But, this may not always be the 'ticket.' Hence, any comment must be suggestive in nature only. I think it might even be disingenuous to highlight this parameter in user messages unless we can also have system information.

See how this gets prickly?

I propose we go one of two ways. 
1. Judging from `dir(psycopg2)` in REPL, that means determining the `psycopg2.OperationalError` class's error and then saying "SSL error (but it may just be the connection).
  - You'd think with this adapter, it's `boto3`, but we implement this by importing the dbt postgres adapter from core.
2. It's too specific and a docs issue for those users it applies to.

All this was indicating to me that we should close this out, but this is frequent enough in Slack/SO that I'm labeling this backlog should someone want to come along and try it. There's just too many moving parts for me to label this a good first issue.
