### ISSUE TITLE
[Feature] DBT Unit tests to support Redshift limitations such as LISTAGG, MEDIAN, PERCENTILE_CONT, etc.

### ISSUE THREAD

**Issue by tanapoln** [dbt-labs/dbt-redshift#807]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

The current DBT Unit tests feature doesn't support Redshift if the SQL in CTE contains functions such as [LISTAGG](https://docs.aws.amazon.com/redshift/latest/dg/r_LISTAGG.html), [MEDIAN](https://docs.aws.amazon.com/redshift/latest/dg/r_MEDIAN.html), [PERCENTILE_CONT](https://docs.aws.amazon.com/redshift/latest/dg/r_PERCENTILE_CONT.html), etc. Those functions must be executed against a user-created-table. However, DBT combines given rows to be part of CTE, which is unsupported by Redshift. You can try SQL below.

```
create temporary table "test_tmpxxxxx" as (
   with test_fixture as (
       select
         cast(1000 as integer) as id,
         cast('menu1' as character varying(500)) as name,
         cast( 1 as integer) as quantity
      union all
      select
         cast(1001 as integer) as id,
         cast('menu2' as character varying(500)) as name,
         cast( 1 as integer) as quantity
      union all
      select
         cast(1003 as integer) as id,
         cast('menu1' as character varying(500)) as name,
         cast( 1 as integer) as quantity
   ),
   agg as (
      SELECT
         LISTAGG(name || ' x ' || quantity, ',') AS option_name_list,
         id
      FROM test_fixture
      GROUP BY id
   )
   select * from agg
);
```

This will error `[XX000] ERROR: One or more of the used functions must be applied on at least one user created tables. Examples of user table only functions are LISTAGG, MEDIAN, PERCENTILE_CONT, etc`

But the query below works fine:

```
create temporary table "test_tmp1234" as (
   SELECT
      cast(1000 as integer) as id,
      cast('menu1' as character varying(500)) as name,
      cast( 1 as integer) as quantity
   union all
   select
      cast(1001 as integer) as id,
      cast('menu2' as character varying(500)) as name,
      cast( 1 as integer) as quantity
   union all
   select
      cast(1000 as integer) as id,
      cast('menu1' as character varying(500)) as name,
      cast( 1 as integer) as quantity
);

with agg as (
   SELECT
      LISTAGG(name || ' x ' || quantity, ',') AS option_name_list,
      id
   FROM test_tmp1234
   GROUP BY id
)
select * from agg;
```

As I mentioned, if all given rows are created as temporary table first, then run the test by referring to it, it will be fine.

This is a feature request to separate DBT unit tests into 2 steps
1. Prepare test fixtures by creating temporary tables
2. Run unit test query by referring to the temporary tables

**Comment by jtcohen6** [comment]
Thanks @tanapoln! Sorry for the delay getting back to you.

Indeed, these functions are **not** supported in the current implementation of dbt unit tests on Redshift.

There was a bit of confusion with the docs update we made to clarify that lack of support, which presented your reproduction case as a viable _workaround_, when really it's an explanation of _why this does not work_:
- https://github.com/dbt-labs/docs.getdbt.com/issues/5430
- https://github.com/dbt-labs/docs.getdbt.com/pull/5508

In order to get this working, I think we'd need to add support for a "materialized" strategy (rather than "CTE") for unit tests:
- https://github.com/dbt-labs/dbt-core/issues/8499

This would also enable us to fully test incremental strategies, among other things. While it's very useful to have this issue so other users can search for it (thank you!), I'm going to consider its actual resolution blocked on implementing dbt-labs/dbt-core#8499.

**Comment by dbeatty10** [comment]
@jtcohen6 just noticed the following in the notes for [Amazon Redshift patch 182](https://docs.aws.amazon.com/redshift/latest/mgmt/cluster-versions.html#cluster-version-182):

> - Updates LISTAGG, MEDIAN, PERCENTILE_CONT and PERCENTILE_DISC to no longer require user-defined tables. Queries that reference catalog tables or that don't reference any tables can also use these functions.

So this _might_ be fixed on Redshift side of things now 🤞
